// Mocks generated by Mockito 5.4.6 from annotations
// in layout_builder_app/test/bloc/layout_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:layout_builder_app/models/layout_model.dart' as _i4;
import 'package:layout_builder_app/repository/layout_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LayoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayoutRepository extends _i1.Mock implements _i2.LayoutRepository {
  MockLayoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, _i4.LayoutModel>> fetchLayouts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchLayouts, []),
            returnValue: _i3.Future<Map<String, _i4.LayoutModel>>.value(
              <String, _i4.LayoutModel>{},
            ),
          )
          as _i3.Future<Map<String, _i4.LayoutModel>>);

  @override
  _i3.Future<void> saveLayout(_i4.LayoutModel? layout) =>
      (super.noSuchMethod(
            Invocation.method(#saveLayout, [layout]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveAllLayouts(Map<String, _i4.LayoutModel>? layouts) =>
      (super.noSuchMethod(
            Invocation.method(#saveAllLayouts, [layouts]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTab(String? tabId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTab, [tabId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
