// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfAGE4QoMZAFLuoib5cOMKYjH9NpK0Vfk',
    appId: '1:1011473604623:web:761b492b350012095d437a',
    messagingSenderId: '1011473604623',
    projectId: 'layout-builder-app',
    authDomain: 'layout-builder-app.firebaseapp.com',
    storageBucket: 'layout-builder-app.firebasestorage.app',
    measurementId: 'G-RF60C3YP9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Re4IKkl4XYb-ZhAKig-ZJvxVVyT8hgg',
    appId: '1:1011473604623:android:9b49296f08f600415d437a',
    messagingSenderId: '1011473604623',
    projectId: 'layout-builder-app',
    storageBucket: 'layout-builder-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMh4fRDvfoZZq0ha4LVvGCo_UZ-u_5oTg',
    appId: '1:1011473604623:ios:ae4f9ff85ef89e145d437a',
    messagingSenderId: '1011473604623',
    projectId: 'layout-builder-app',
    storageBucket: 'layout-builder-app.firebasestorage.app',
    iosBundleId: 'com.example.layoutBuilderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMh4fRDvfoZZq0ha4LVvGCo_UZ-u_5oTg',
    appId: '1:1011473604623:ios:ae4f9ff85ef89e145d437a',
    messagingSenderId: '1011473604623',
    projectId: 'layout-builder-app',
    storageBucket: 'layout-builder-app.firebasestorage.app',
    iosBundleId: 'com.example.layoutBuilderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfAGE4QoMZAFLuoib5cOMKYjH9NpK0Vfk',
    appId: '1:1011473604623:web:a4ad4834efbd2a085d437a',
    messagingSenderId: '1011473604623',
    projectId: 'layout-builder-app',
    authDomain: 'layout-builder-app.firebaseapp.com',
    storageBucket: 'layout-builder-app.firebasestorage.app',
    measurementId: 'G-6JQKD5ZX1T',
  );
}
